[package]
name = "parseutils"
version = "0.1.0"
authors = ["Thomas Doylend <tmdoylend@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-normalization = "^0.1.8"
